# Lista de Exercícios do Class

In [1]:
import numpy as np
import pandas as pd

## LC | Numpy - Manipulação de Arrays

### 1) 
Printe os elementos dos seguintes dois vetores usando apenas um for:

```python
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
```

Depois, faça o mesmo usando numpy (usando a função nditer) e deixe um comentário sobre a diferença dos dois métodos.

```python
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
```

In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [13]:
# loop "for"
for element in arr:
    print(element)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [15]:
# np.nditer()
for element in np.nditer(arr):
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12


**Resp**: Para o loop ``for``, os elementos iterados são listas, no caso, [1,2,3], [4,5,6], etc. Para o ``np.nditer(arr)`` o valor iterado são os elementos dentro de outras listas.

### 2)
Enunciado
Peça para o usuário uma lista com as comidas favoritas dele, depois transforme isso em um objeto numpy. Agora transformado, elimine todas as comidas que começam com uma vogal. Mostre o resultado.

Exemplo:
```python
Entrada: [maçã, uva, morango, melancia, acelga]
```

```python
Saída: [maçã, morango, melancia]
```

In [2]:
comidas = ["maçã", "uva", "morango", "melancia", "acelga"]
comidas = np.array(comidas)

In [7]:
comidas

array(['maçã', 'uva', 'morango', 'melancia', 'acelga'], dtype='<U8')

In [4]:
# filtrar strings que começam com vogal
filt_cons = [comida for comida in comidas if comida[0] not in ["a","e","i","o","u"]]
filt_cons

['maçã', 'morango', 'melancia']

In [12]:
# Deu certo
filt_1 = np.char.startswith(comidas, "a")
filt_2 = np.char.startswith(comidas, "e")
filt_3 = np.char.startswith(comidas, "i")
filt_4 = np.char.startswith(comidas, "o")
filt_5 = np.char.startswith(comidas, "u")

comidas[~filt_1 & ~filt_2 & ~filt_3 & ~filt_4 & ~filt_5]

array(['maçã', 'morango', 'melancia'], dtype='<U8')

### 3)
Imprima a dimensão dos seguintes objetos numpy:
```python
a = np.array(2)
```
```python
b = np.array([1, 2, 3, 4, 5])
```
```python
c = np.array([[1, 2, 3], [4, 5, 6]])
```
```python
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
```

In [35]:
a = np.array(2)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [39]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### 4)
Transforme o array em uma matriz 4 por 3 utilizando numpy.

```python
arr = [1, 2, 3, 4, 'Amelia, 'Bruna, 'Carolina', 'Débora', True, False, False, True]
```
Depois, faça o mesmo para uma matriz 3 por 4.

In [50]:
# Matriz 4x3
arr = np.array([1, 2, 3, 4, 'Amelia', 'Bruna', 'Carolina', 'Débora', True, False, False, True]).reshape(4,3)
arr

array([['1', '2', '3'],
       ['4', 'Amelia', 'Bruna'],
       ['Carolina', 'Débora', 'True'],
       ['False', 'False', 'True']], dtype='<U11')

In [51]:
# Matriz 3x4
arr.reshape(3,4)

array([['1', '2', '3', '4'],
       ['Amelia', 'Bruna', 'Carolina', 'Débora'],
       ['True', 'False', 'False', 'True']], dtype='<U11')

### 5)
Transforme o seguinte array em uma matriz 3D 3x3x3:
```python
arr = range(27)
```
Deixe um comentário explicando o que significa uma matriz 3D.

In [53]:
arr = np.array(range(27)).reshape(3,3,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

**Resp**: matriz 3D seria um conjunto de números de 3 camadas de uma matriz 3x3

### 6)
Tente transformar o seguinte array em uma matriz 3x3x3
```python
arr = [1, 2, 3, 4, 5, 6, 7, 8]
```
Funciona? Se sim, explique o motivo. Se não, explique o erro.

In [54]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(3,3,3)

ValueError: cannot reshape array of size 8 into shape (3,3,3)

**Resp**: o número de elementos no array deverá ser igual à 27

### 7)
Percorra o seguinte array utilizando for encaixado:
```python
arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
```
Agora, percorra o mesmo array utilizando a função nditer de numpy.

In [55]:
arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [56]:
# utilizando for
for element in arr:
    print(element)

[[1, 2], [3, 4]]
[[5, 6], [7, 8]]


In [58]:
# utilizando nditer
for element in np.nditer(arr):
    print(element)

(array(1), array(5))
(array(2), array(6))
(array(3), array(7))
(array(4), array(8))


### 8)
Percorra os indexes do seguinte array utilizando for encaixado:
```python
arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
```
Agora faça o mesmo trabalho utilizando a função ndenumerate.

In [34]:
arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [35]:
for element in arr:
    print(element)

[[1, 2], [3, 4]]
[[5, 6], [7, 8]]


In [36]:
for index, element in np.ndenumerate(arr):
    print(index, element)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


### 9)
Junte os dois seguintes arrays na horizontal:
```python
arr1 = [1, 2, 3]
```
```python
arr2 = [4, 5, 6]
```
Depois, os junte verticalmente.

In [64]:
arr1 = [1, 2, 3]
arr2 = [4, 5, 6]

In [67]:
# juntar na horizontal
np.hstack([arr1, arr2])

array([1, 2, 3, 4, 5, 6])

In [68]:
# juntar na vertical
np.vstack([arr1, arr2])

array([[1, 2, 3],
       [4, 5, 6]])

### 10)
DESAFIO: Utilizando manipulação de arrays, ache os indexes do array cujo valor possua apenas 2 vogais no nome usando numpy.
```python
frutas = ['banana', 'morango', 'uva', 'pitaia', 'abacate', 'abacaxi', 'acerola', 'jenipapo', 'kiwi']
```

In [15]:
# Manipular por listas: Muito complicado fazer isso com numpy
def count_vogal(word):
    soma = 0
    for letter in word:
        if letter in "aeiou":
            soma += 1
    return soma

frutas = ['banana', 'morango', 'uva', 'pitaia', 'abacate', 'abacaxi', 'acerola', 'jenipapo', 'kiwi']
frutas = np.array([fruta for fruta in frutas if count_vogal(fruta) == 2])

frutas

array(['uva', 'kiwi'], dtype='<U4')

### 11) Usando ``.split()``
a) Tranforme o seguinte array 2D em dois arrays 2D:
```python
arr = [[1, 2], [3, 4], [5, 6], [7, 8]]
```
b) Transforme o seguinte array em três arrays com apenas uma coluna:
```python
arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
```

In [26]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
arrays = np.split(arr, 2)
print(arrays[0])
print()
print(arrays[1])

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arrays2 = np.split(arr, 3)
print(arrays2[0])
print()
print(arrays2[1])
print()
print(arrays2[2])

[[1 2 3]]

[[4 5 6]]

[[7 8 9]]


### 12)
DESAFIO: Utilizando manipulação de arrays, vamos seguir um conjunto de passos para organizar alguns dados. Teremos nesse seguinte array uma ordem que segue:
```python
[Nome do aluno, idade, 'gênero', signo, altura, nota do 1° semestre, nota do 2° bimestre, se está ou não inscrito no próximo ano da escola, nome do outro aluno, idade do outro aluno...]
```
```python
arr = ['Amélia', 13, 'F', 'peixes', 1.51, 9, 7, True, 'Bruno', 14, 'O', 'leão', 1.60, 4, 10, False, 'João', 14, 'M', 'escorpião', 1.58, 8, 9, True, 'Jordana', 13, 'F', 'escorpião', 1.72, 9, 9, False]
```
a) Enumere os indexes de todas as informações que são do tipo string.

b) Separe essas informações do objeto arr de forma que cada aluno tenha seu próprio array.

c) Separe em duas colunas, a primeira com o nome, a idade, o gênero e o signo e a segunda com a altura, nota do primeiro bimestre, nota do segundo bimestre e se está ou não inscrito no próximo ano.

d) Elimine o gênero de todos os arrays cujos alunos tem menos de 14 anos.

## LC | Numpy 1

### 1)
Dado o array:
```python
arr = np.arange(50)
```
Selecione a alternativa INCORRETA na utilização de filtros e máscaras neste Numpy array.

In [37]:
arr = np.arange(50)
arr_atualizado = arr[(arr != 1) | (arr != 3)]
print(arr_atualizado)

# Resp: Não altera o array original

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


## 2)
Agora, vamos explorar os arrays aleatórios e máscaras. Faça o que se pede:

a) Crie um array aleatório de 15 itens entre 0 e 100;

b) Qual o maior número do array?

c) Qual a sua posição?

d) Verifique quais números do array são maior que 10;

e) Salve em uma nova lista apenas os itens entre 10 e 30.

In [70]:
# a)
array = np.random.randint(0, 100, 15)
array

array([77, 41, 64, 10, 21, 47, 88, 19, 47, 45, 56, 96, 10, 66, 59])

In [72]:
# b)
array.max()

96

In [77]:
# c)
np.where(array == array.max())

(array([11], dtype=int64),)

In [78]:
# d)
array[array > 10]

array([77, 41, 64, 21, 47, 88, 19, 47, 45, 56, 96, 66, 59])

In [82]:
# e)
new_array = array[(array > 10) & (array < 30)]
new_array

array([21, 19])

## 3)
Nosso próximo foco serão as matrizes. Faça o que se pede:

a) Gere uma matriz (3,2) com números linearmente espaçados entre 0 e 100 e intervalos de 20, usando ```np.linspace()```;

b) Gere uma matriz aleatória (5,2) com números entre 0 e 100;

c) Crie um array com as dimensões apropriadas que, quando multiplicado pela matriz do item a), devolva essa mesma matriz. Use o método ```np.matmul()```.

In [40]:
# a)
arr1 = np.linspace(0, 100, 6)

In [41]:
arr1

array([  0.,  20.,  40.,  60.,  80., 100.])

In [42]:
arr1.shape

(6,)

In [43]:
# b)
array = np.random.randint(0, 100, 10).reshape(5,2)
array

array([[42, 31],
       [54, 83],
       [78, 27],
       [27, 26],
       [66, 57]])

In [44]:
# c)
arr2 = np.ones(6)
arr2

array([1., 1., 1., 1., 1., 1.])

In [47]:
# Não entendi
np.matmul(arr1, arr2)

300.0

## LC | Pandas 1

### 1)
Em um concurso público foram contabilizados os números de pessoas inscritas (até a data inicialmente estabelecida para a inscrição) segundo os níveis de escolaridade: fundamental completo, médio completo, superior completo e pós-graduação completa. Segue abaixo a tabela com os valores observados.

|Nível de escolaridade|Inscritos|
|-|-|
|Fundamental completo|	451|
|Médio completo|	627|
|Superior completo	|292|
|Pós-graduação completa	|95|

Com base na tabela acima, crie uma Series com esses valores e calcule:

(a) O número total de inscritos.

(b) Número inscritos que possuem, pelo menos, o superior completo.

(c) Suponha que a inscrição foi prorrogada e, com isso, foi obtido um número adicional de inscrições: 68, 93, 22 e 0 inscritos a mais em cada uma das categorias de escolaridade apresentados na tabela acima (na mesma ordem). Assim, crie uma nova Series com esses valores.

(d) Utilizando as duas Series que você tem, calcule o número total de inscritos após a prorrogação do período de inscrições.

In [102]:
concurso = pd.read_clipboard()
concurso

Nível de escolaridade  Inscritos
0    Fundamental completo        451
1          Médio completo        627
2       Superior completo        292
3  Pós-graduação completa         95

In [103]:
# a)
concurso["Inscritos"].sum()

1465

In [105]:
# b)
concurso[(concurso["Nível de escolaridade"] == "Superior completo") |
         (concurso["Nível de escolaridade"] == "Pós-graduação completa")].sum()

Nível de escolaridade    Superior completoPós-graduação completa
Inscritos                                                    387
dtype: object

In [107]:
# c) e d)
prorrogados = np.array([68, 93, 22, 0])
concurso["Inscritos"] = concurso["Inscritos"] + prorrogados

In [108]:
concurso

Nível de escolaridade  Inscritos
0    Fundamental completo        519
1          Médio completo        720
2       Superior completo        314
3  Pós-graduação completa         95

### 2)
Uma turma de cinco alunos foi submetida a uma avaliação e a nota de cada um dos alunos é apresentada na tabela abaixo:

|Nome do Aluno|	Nota|
|-|-|
|Wilfred|	2|
|Abbie|	7|
|Harry|	5.5|
|Julia|	10|
|Carrie|	6.2|

(a) Crie uma Series com os valores da tabela acima.

(b) Retorne o número de alunos que foram aprovados (considerando que a nota mínima para a aprovação é 7).

(c) Qual foi a nota média da turma.

(d) Obtenha o nome dos alunos que tiraram notas acima da média da turma.



In [128]:
# a)
alunos = pd.read_clipboard()

In [129]:
aluno = alunos["Nome do Aluno"]

In [130]:
aluno

0    Wilfred
1      Abbie
2      Harry
3      Julia
4     Carrie
Name: Nome do Aluno, dtype: object

In [131]:
nota = alunos["Nota"]

In [132]:
nota

0     2.0
1     7.0
2     5.5
3    10.0
4     6.2
Name: Nota, dtype: float64

In [133]:
# b)
alunos[alunos["Nota"] > 7]

Nome do Aluno  Nota
3         Julia  10.0

In [134]:
# c)
nota.mean()

6.14

In [135]:
# d)
alunos[alunos["Nota"] > nota.mean()]

Nome do Aluno  Nota
1         Abbie   7.0
3         Julia  10.0
4        Carrie   6.2

### 3)
Crie um objeto DataFrame que contenha os dados da tabela abaixo, os quais se referem ao peso, altura e idade de cinco pessoas:

|Peso (kg)|Altura (cm)|Idade|
|-|-|-|
|72|180|31|
|80	|170|21|
|60	|175|16|
|90	|174|28|
|100|185|23|

Com base no DataFrame criado, realize o que pedido nos itens abaixo:

(a) Visualize apenas os dados da coluna que contém a altura das pessoas.

(b) Obtenha a idade média das pessoas.

(c) Obtenha os dados das pessoas que estão abaixo da altura média.

(d) Crie um nova coluna no DataFrame que contenha o IMC (Índice de Massa Corporal) de cada pessoa.

(e) Remova a coluna que contém a idade das pessoas.

(f) Salve esses dados do DataFrame em um arquivo csv.



In [48]:
# dataframe
imc = pd.read_clipboard()

In [49]:
imc

Peso (kg)  Altura (cm)  Idade
0         72          180     31
1         80          170     21
2         60          175     16
3         90          174     28
4        100          185     23

In [50]:
# a)
imc["Altura (cm)"]

0    180
1    170
2    175
3    174
4    185
Name: Altura (cm), dtype: int64

In [51]:
# b)
imc["Idade"].mean()

23.8

In [52]:
# c) Abaixo da altura média
imc[imc["Altura (cm)"] < imc["Altura (cm)"].mean()]

Peso (kg)  Altura (cm)  Idade
1         80          170     21
2         60          175     16
3         90          174     28

In [61]:
# d)
imc["IMC"] = imc["Peso (kg)"] / (imc["Altura (cm)"]/100)**2
imc

Peso (kg)  Altura (cm)  Idade        IMC
0         72          180     31  22.222222
1         80          170     21  27.681661
2         60          175     16  19.591837
3         90          174     28  29.726516
4        100          185     23  29.218408

In [63]:
# e)
imc.drop("Idade", axis = 1, inplace = True)
imc

Peso (kg)  Altura (cm)        IMC
0         72          180  22.222222
1         80          170  27.681661
2         60          175  19.591837
3         90          174  29.726516
4        100          185  29.218408

In [64]:
# f)
imc.to_csv("IMC.csv", index=False)

### 4)
Carregue, em um objeto DataFrame, o arquivo CSV que você salvou no item (f) da questão anterior. Em seguida,

(a) Crie uma nova coluna que contenha o nome das pessoas (sinta-se à vontade para atribuir os nomes que preferir).

(b) Defina a nova coluna criada (com os nomes) como o índice (index) do seu DataFrame.

(c) Obtenha o nome das pessoas que são classificadas com Sobrepeso (IMC entre 25 e 29,9).

In [65]:
imc = pd.read_csv("IMC.csv")

In [70]:
# a) e b)
imc['Nome'] = ["João", "Maria", "Carlos", "José", "Ana"]
imc.set_index('Nome', inplace = True)
imc

Peso (kg)  Altura (cm)        IMC
Nome                                     
João           72          180  22.222222
Maria          80          170  27.681661
Carlos         60          175  19.591837
José           90          174  29.726516
Ana           100          185  29.218408

In [75]:
# c)
imc[(imc["IMC"] > 25) & (imc["IMC"] < 29.9)].index

Index(['Maria', 'José', 'Ana'], dtype='object', name='Nome')

### 5)
Carregue, em um objeto DataFrame, o mesmo dataset que você salvou na Questão 3. Em seguida,

(a) Adicione uma nova coluna nesse DF chamada Classificação, que contenha a classificação de cada indivíduo, de acordo com o seu IMC. Para isso, consulte a tabela abaixo.

|IMC|	Classificação|	Obesidade (grau)|
|-|-|-|
|Menor que 18,5|	Magreza|	0|
|Entre 18,5 e 24,9|	Normal	|0|
|Entre 25,0 e 29,9	|Sobrepeso	|I|
|Entre 30,0 e 39,9	|Obesidade	|II|
|Maior que 40,0	|Obesidade Grave|	III|

(b) Salve em DataFrame no formato xlsx.

In [76]:
imc = pd.read_csv("IMC.csv")

In [77]:
imc

Peso (kg)  Altura (cm)        IMC
0         72          180  22.222222
1         80          170  27.681661
2         60          175  19.591837
3         90          174  29.726516
4        100          185  29.218408

In [78]:
# a)
imc["Classificação"] = ["Normal", "Sobrepeso", "Normal", "Sobrepeso", "Sobrepeso"]
imc

Peso (kg)  Altura (cm)        IMC Classificação
0         72          180  22.222222        Normal
1         80          170  27.681661     Sobrepeso
2         60          175  19.591837        Normal
3         90          174  29.726516     Sobrepeso
4        100          185  29.218408     Sobrepeso

## LC | Pandas 2

### 1)
O arquivo ```avocado.csv``` consiste em um dataset que contém dados sobre vendas de abacates (avocado, em inglês) em diversas regiões dos Estados Unidos. Essa dataset contém as seguintes colunas:

```Date``` - a data da observação

```AveragePrice``` - o preço médio de um único abacate

```year``` - o ano

```region``` - a cidade ou região da observação

```Total Volume``` - volume total de abacates vendidos

Além das informações acima, contidas no arquivo ```avocado.csv```, o tipo do abacate (convencional ou orgânico) também seria uma informação importante para a sua análise. Suponhamos que você conseguiu essas informações para cada uma das observações do arquivo ```avocado.csv```, na mesma ordem, e salvou-as no arquivo ```avocado_type.csv```. Portanto, tudo o que você precisa é juntar esses dois arquivos em um mesmo DataFrame. E, em seguida, salve-o em um arquivo csv.

PS. Caso queira criar uma Series com os dados aleatórios para o tipo de abacate, utilize o código abaixo:

```python
tipos = pd.Series(np.random.randint(0, 2, df_avocado.shape[0]))
tipos = tipos.map({0: 'convencional', 1:'orgânico'})
```


In [21]:
avocado = pd.read_csv("avocado.csv")
tipos = pd.read_csv("avocado_type.csv")

In [24]:
avocado["Type"] = tipos
avocado

Date  AveragePrice  Total Volume  year            region  \
0      2015-12-27          1.33      64236.62  2015            Albany   
1      2015-12-20          1.35      54876.98  2015            Albany   
2      2015-12-13          0.93     118220.22  2015            Albany   
3      2015-12-06          1.08      78992.15  2015            Albany   
4      2015-11-29          1.28      51039.60  2015            Albany   
...           ...           ...           ...   ...               ...   
18244  2018-02-04          1.63      17074.83  2018  WestTexNewMexico   
18245  2018-01-28          1.71      13888.04  2018  WestTexNewMexico   
18246  2018-01-21          1.87      13766.76  2018  WestTexNewMexico   
18247  2018-01-14          1.93      16205.22  2018  WestTexNewMexico   
18248  2018-01-07          1.62      17489.58  2018  WestTexNewMexico   

               Type  
0      conventional  
1      conventional  
2      conventional  
3      conventional  
4      conventional  
...             ...  
18244       organic  
18245       organic  
18246       organic  
18247       organic  
18248       organic  

[18249 rows x 6 columns]

### 2)
Carregue o arquivo csv que você salvou na questão anterior e, em seguida, obtenha o que é solicitado nos itens elencados abaixo:

(a) A quantidade de abacates do tipo convecional e do tipo orgânico.

(b) A quantidade de registros (linhas) de abacates vendidos para cada região.

(c) Para que todos os labels das colunas fiquem padronizados, renomeie aqueles que estão iniciando em letra minúscula para que iniciem em letra maiúscula.

(d) Uma vez que você já possui uma coluna com a data, remova a coluna que apresenta o ano.

In [28]:
# a)
avocado["Type"].value_counts()

conventional    9126
organic         9123
Name: Type, dtype: int64

In [ ]:
# b)


### 3)
Carregue, em um objeto DataFrame, o mesmo dataset que você salvou na questão Q1, agrupe os dados do DF pelo tipo do abacate e, em seguida, obtenha:

(a) A volume total de abacates vendidos para cada tipo.

(b) O preço médio dos abacates vendidos para cada tipo.

### 4)
O arquivo ```googleplaystore.csv``` é um dataset que contém diversas informações sobre aplicativos disponíveis para download na Google Play Store. Logo após, verifique se existem dados duplicados e/ou ausentes nesse dataset.

Caso existam dados duplicados, remova-os. Caso existam dados ausentes, você pode removê-los ou pensar em alguma maneira de preenchê-los.

In [8]:
play = pd.read_csv("googleplaystore.csv", sep = ",")
play.shape

(10841, 13)

In [15]:
play.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...  
10836    False
10837    False
10838    False
10839    False
10840    False
Length: 10841, dtype: bool

### 5)
O arquivo ```houses_to_rent.csv``` consiste em um dataset que contém dados sobre casas para alugar no Brasil. Carregue-o em um objeto DataFrame e verifique os dados contidos nas colunas desse DF (você pode utilizar os métodos ```head```, ```tail``` e ```info```). Logo após, verifique se existem dados duplicados e/ou ausentes nesse dataset.

Caso existam dados duplicados, remova-os. Caso existam dados ausentes, você pode removê-los ou pensar em alguma maneira de preenchê-los.

In [17]:
houses = pd.read_csv("houses_to_rent.csv")


AttributeError: 'DataFrame' object has no attribute 'unique'