### Alguns conceitos de Linalg

In [41]:
import numpy as np
from numpy.linalg import solve, inv

In [2]:
a = np.array([1,2,3])

In [3]:
a.shape

(3,)

In [4]:
# transpose()
a.T.shape

(3,)

In [5]:
a*a

array([1, 4, 9])

#### For mathematical purposes, a must be reshape for calculations. Operations must be done in matrix (i,j)

In [6]:
a.reshape(3,1)

array([[1],
       [2],
       [3]])

In [7]:
a2 = np.array([[1],[2],[3]])
a2

array([[1],
       [2],
       [3]])

In [8]:
a2*a2

array([[1],
       [4],
       [9]])

In [9]:
a2.shape

(3, 1)

In [10]:
a3 = np.array([[1,2,3]])
a3

array([[1, 2, 3]])

In [11]:
a3*a3

array([[1, 4, 9]])

In [12]:
a3.shape

(1, 3)

#### Other operations

In [13]:
a2*a2

array([[1],
       [4],
       [9]])

In [14]:
a3*a3

array([[1, 4, 9]])

In [15]:
a2*a3

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [16]:
a2.T == a3

array([[ True,  True,  True]])

#### Linalg.solve(a,b): a.x=b

In [17]:
a = np.array([[1,2],[3,5]])
b = np.array([1.,2.])

In [18]:
x = np.linalg.solve(a,b)
x

array([-1.,  1.])

In [19]:
np.dot(a,x)

array([1., 2.])

In [20]:
b

array([1., 2.])

### Convertendo vetores em matrizes

In [21]:
a1 = np.matrix(a)
a1.shape # uma linha e três colunas

(2, 2)

In [22]:
a1.T.shape

(2, 2)

#### Exemplos

In [30]:
A = np.array([1,2,3])
B = np.array([[1,1,1],[2,2,2]])
A.shape, B.shape

((3,), (2, 3))

In [27]:
C = A*B
C

array([[1, 2, 3],
       [2, 4, 6]])

In [31]:
D = B*A
D

array([[1, 2, 3],
       [2, 4, 6]])

In [32]:
C == D

array([[ True,  True,  True],
       [ True,  True,  True]])

#### Exemplo 1 - Matrizes e Estatísticas

||Lógica|Cálculo|Python|Inglês|

|Turma A|6|5|9|6|
|Turma B|8|9|8|7|
|Turma C|9|9|8|6|
|Turma D|7|8|6|9|

In [34]:
T = np.array(([6,5,9,6],[8,9,8,7],[9,9,8,6],[7,8,6,9]))
T

array([[6, 5, 9, 6],
       [8, 9, 8, 7],
       [9, 9, 8, 6],
       [7, 8, 6, 9]])

In [37]:
mean_logic = T[:,0].mean()
mean_calc = T[:,1].mean()
mean_py = T[:,2].mean()
mean_ing = T[:,3].mean()
mean_logic, mean_calc, mean_py, mean_ing

(7.5, 7.75, 7.75, 7.0)

In [38]:
mean_A = T[0,:].mean()
mean_B = T[1,:].mean()
mean_C = T[2,:].mean()
mean_D = T[3,:].mean()
mean_A, mean_B, mean_C, mean_D

(6.5, 8.0, 8.0, 7.5)

In [40]:
med_fac = T.mean() # média
std_fac = T.std() # desvio padrão
med_fac, std_fac

(7.5, 1.3228756555322954)

#### Exemplo 2 - Matrizes e inversa

In [42]:
C = np.array(([1,2],[3,4]))
D = inv(C)
C, D

(array([[1, 2],
        [3, 4]]),
 array([[-2. ,  1. ],
        [ 1.5, -0.5]]))

In [45]:
np.dot(C,D) # Matriz identidade

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

#### Exemplo 3 - Sistemas lineares

In [46]:
A = np.array(([1, -2],[1,3]))
B = np.array(([5,2]))
A, B

(array([[ 1, -2],
        [ 1,  3]]),
 array([5, 2]))

In [48]:
C = inv(A).dot(B)
C

array([ 3.8, -0.6])