In [2]:
import pandas as pd
import numpy as np

In [3]:
df1 = pd.DataFrame({'A':[1,2,3],
                   'B':[4,5,6],
                   'C':[7,8,9]},
                   index = ['a','b','c'])

In [4]:
df1

A  B  C
a  1  4  7
b  2  5  8
c  3  6  9

In [9]:
df2 = pd.DataFrame({'A':[1,2],
                   'B':[4,5],
                   'C':[7,8]},
                   index = ['a','b'])

In [15]:
df2.append(df1)

A  B  C
a  1  4  7
b  2  5  8
a  1  4  7
b  2  5  8
c  3  6  9

In [16]:
df2

A  B  C
a  1  4  7
b  2  5  8

In [17]:
df2.reindex(['a','b','c'])

A    B    C
a  1.0  4.0  7.0
b  2.0  5.0  8.0
c  NaN  NaN  NaN

In [21]:
df2.loc[['a','b']]

A  B  C
a  1  4  7
b  2  5  8

In [23]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
        'year':[2000,2001,2002,2000,2001,2002],
        'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2000, 2001, 2002],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [27]:
frame = pd.DataFrame(data,columns=['year','state','pop','debt'],index = ['one','two','three','four','five','six'])
frame

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2000  Nevada  2.4  NaN
five   2001  Nevada  2.9  NaN
six    2002  Nevada  3.2  NaN

In [1]:
frame.columns
frame.index

NameError: name 'frame' is not defined

In [30]:
frame.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [31]:
frame.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [44]:
frame['debt']= np.arange(3.,step=0.5)

In [45]:
frame

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   0.5
three  2002    Ohio  3.6   1.0
four   2000  Nevada  2.4   1.5
five   2001  Nevada  2.9   2.0
six    2002  Nevada  3.2   2.5

In [38]:
np.arange?

In [46]:
val = pd.Series([-1.2,-1.5,-1.7],index = ['two','four','five'])

In [47]:
frame['debt']=val

In [48]:
frame

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2000  Nevada  2.4  -1.5
five   2001  Nevada  2.9  -1.7
six    2002  Nevada  3.2   NaN

In [49]:
frame['eastern'] = frame.state == 'Ohio'

In [50]:
frame

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2000  Nevada  2.4  -1.5    False
five   2001  Nevada  2.9  -1.7    False
six    2002  Nevada  3.2   NaN    False

In [51]:
del(frame['eastern'])

In [52]:
frame

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2000  Nevada  2.4  -1.5
five   2001  Nevada  2.9  -1.7
six    2002  Nevada  3.2   NaN

In [53]:
val = pd.Series([-2.1,-1.5,-1.7],index = ['two','four','five'])

In [54]:
frame

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2000  Nevada  2.4  -1.5
five   2001  Nevada  2.9  -1.7
six    2002  Nevada  3.2   NaN

In [18]:
f = np.arange(8)
t = np.array([3,4,5,6,3,7,8,1])
f
t

array([3, 4, 5, 6, 3, 7, 8, 1])

In [17]:
f

array([0, 1, 2, 3, 4, 5, 6, 7])

In [30]:
np.dot(f,t)

134

In [31]:
x = [1,2,3]
y = [4,5,6]
np.cross(x,y)

array([-3,  6, -3])

In [32]:
data = pd.DataFrame(np.arange(16).reshape(4,4),
                    index = ['Ohio','Colorado','Utah','New York'],
                    columns = ['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [45]:
data.loc[['Colorado','Utah'],['one','three']]

one  three
Colorado    4      6
Utah        8     10

In [42]:
data.iloc[[1,2],[0,2]]

one  three
Colorado    4      6
Utah        8     10

In [56]:
data2 = data.drop('Utah').drop('two',axis=1).drop('one',axis='columns')
data2

three  four
Ohio          2     3
Colorado      6     7
New York     14    15

In [65]:
obj = pd.Series(np.arange(4),index=['a','b','c','d'])
obj

a    0
b    1
c    2
d    3
dtype: int32

In [68]:
obj[['a','b']]

a    0
b    1
dtype: int32

In [72]:
obj.describe()

count    4.000000
mean     1.500000
std      1.290994
min      0.000000
25%      0.750000
50%      1.500000
75%      2.250000
max      3.000000
dtype: float64

In [76]:
obj['b':'c']

b    1
c    2
dtype: int32

In [3]:
# Cadastro da loja A
cadastro_a = {'Id':['AA2930','BB4563','CC2139','DE2521','GT3462','HH1158'],
              'Nome':['Victor','Amanda','Bruna','Carlos','Ricardo','Maria'],
              'Idade':[20,35,40,54,30,27],
              'CEP':['00092-0290','11111-111','22222-888','00000-999','88888-111','77777-666']
             }
cadastro_a = pd.DataFrame(cadastro_a, columns = ['Id','Nome','Idade','CEP'])
cadastro_a

Id     Nome  Idade         CEP
0  AA2930   Victor     20  00092-0290
1  BB4563   Amanda     35   11111-111
2  CC2139    Bruna     40   22222-888
3  DE2521   Carlos     54   00000-999
4  GT3462  Ricardo     30   88888-111
5  HH1158    Maria     27   77777-666

In [4]:
# Cadstro da loja B
cadastro_b = {'Id':['CC9999','EF4488','DD9999','GT3462','HH1158'],
              'Nome':['Marcos','Patrícia','Ericka','Ricardo','Maria'],
              'Idade':[19,30,22,30,27],
              'CEP':['00092-029','11111-111','11111-888','88888-111','77777-666']
             }
cadastro_b = pd.DataFrame(cadastro_b, columns = ['Id','Nome','Idade','CEP'])
cadastro_b

Id      Nome  Idade        CEP
0  CC9999    Marcos     19  00092-029
1  EF4488  Patrícia     30  11111-111
2  DD9999    Ericka     22  11111-888
3  GT3462   Ricardo     30  88888-111
4  HH1158     Maria     27  77777-666

In [5]:
# Registro de compras de todas unidades
compras  = {'Id':['AA2930','EF4488','CC2139','EF4488','CC9999','AA2930','HH1158','HH1158'],
            'Data':['2019-01-01','2019-01-30','2019-01-30','2019-02-01','2019-02-20','2019-03-15','2019-04-01','2019-04-10'],
            'Valor':[200,100,40,150,300,25,50,500]
           }
compras = pd.DataFrame(compras, columns = ['Id','Data','Valor'])
compras

Id        Data  Valor
0  AA2930  2019-01-01    200
1  EF4488  2019-01-30    100
2  CC2139  2019-01-30     40
3  EF4488  2019-02-01    150
4  CC9999  2019-02-20    300
5  AA2930  2019-03-15     25
6  HH1158  2019-04-01     50
7  HH1158  2019-04-10    500

In [8]:
cadastro = pd.merge(cadastro_a,cadastro_b, how='outer')
cadastro

Id      Nome  Idade         CEP
0  AA2930    Victor     20  00092-0290
1  BB4563    Amanda     35   11111-111
2  CC2139     Bruna     40   22222-888
3  DE2521    Carlos     54   00000-999
4  GT3462   Ricardo     30   88888-111
5  HH1158     Maria     27   77777-666
6  CC9999    Marcos     19   00092-029
7  EF4488  Patrícia     30   11111-111
8  DD9999    Ericka     22   11111-888

In [18]:
# Não deixar de fora quem não fez nenhuma compra
compras_clientes = pd.merge(cadastro,compras, how='outer')
compras_clientes

Id      Nome  Idade         CEP        Data  Valor
0   AA2930    Victor     20  00092-0290  2019-01-01  200.0
1   AA2930    Victor     20  00092-0290  2019-03-15   25.0
2   BB4563    Amanda     35   11111-111         NaN    NaN
3   CC2139     Bruna     40   22222-888  2019-01-30   40.0
4   DE2521    Carlos     54   00000-999         NaN    NaN
5   GT3462   Ricardo     30   88888-111         NaN    NaN
6   HH1158     Maria     27   77777-666  2019-04-01   50.0
7   HH1158     Maria     27   77777-666  2019-04-10  500.0
8   CC9999    Marcos     19   00092-029  2019-02-20  300.0
9   EF4488  Patrícia     30   11111-111  2019-01-30  100.0
10  EF4488  Patrícia     30   11111-111  2019-02-01  150.0
11  DD9999    Ericka     22   11111-888         NaN    NaN

In [19]:
pd.DataFrame(compras_clientes.groupby(['Id','Nome'])['Valor'].sum())

Valor
Id     Nome           
AA2930 Victor    225.0
BB4563 Amanda      0.0
CC2139 Bruna      40.0
CC9999 Marcos    300.0
DD9999 Ericka      0.0
DE2521 Carlos      0.0
EF4488 Patrícia  250.0
GT3462 Ricardo     0.0
HH1158 Maria     550.0

In [20]:
# Indexação
v = [1,2,3,4,5]

In [22]:
list?